name: 'Parameter Store'
description: 'Parameter store'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
    default: '931670397156'
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
    default: 'github-actions'
  aws_region:
    description: 'Aws region'
    required: true
    default: 'us-east-1'
  terraform_bucket_name:
    description: 'Bucket'
    required: true
    default: 'terraform-orbit'
  modulo:
    description: 'Module'
    required: true
  repository:
    description: 'Repository'
    required: true
  tag:
    description: 'tag'
    required: true

runs:
  using: composite
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}

  - name: Checkout code
    uses: actions/checkout@v4
    with:
        repository: 'orbitspot/actions'
        path: code
        ref: '${{ inputs.tag }}'

  - name: Download Artifact Variables
    uses: actions/download-artifact@v4
    with:
        name: variables
        path: code/terraform/parameter-store

  - name: Download Artifact
    uses: actions/download-artifact@v4
    with:
        name: secrets
        path: code/terraform/parameter-store
  
  - name: Install Terraform
    shell: bash
    run: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
      terraform --version

  - name: Verify Terraform Installation
    shell: bash
    run: terraform --version

  - name: Terraform Init
    shell: bash
    run: |
      ls
      cd code/terraform/parameter-store && ls
      terraform init -backend-config=bucket=${{ inputs.terraform_bucket_name }} -backend-config=key=parameter-store/${{ github.event.repository.name }}/${{ github.ref_name }}.tfstate -backend-config=region=us-east-1 -no-color
      
  - name: Terraform Plan
    shell: bash
    env:
      TF_VAR_region: ${{ inputs.aws_region }}
      TF_VAR_modulo: ${{ inputs.modulo }}
      TF_VAR_repository: ${{ inputs.repository }}
    run: |
      cd code/terraform/parameter-store
      terraform plan -no-color

  - name: Terraform Apply
    shell: bash
    env:
      TF_VAR_region: ${{ inputs.aws_region }}
      TF_VAR_modulo: ${{ inputs.modulo }}
      TF_VAR_repository: ${{ inputs.repository }}
    run: |
      cd code/terraform/parameter-store
      terraform apply -auto-approve -no-color

