name: "Prepare Helm Values"
description: "Prepara values.yaml com variáveis substituídas"
inputs:
  chart_type:
    description: "Tipo do chart (ex: node_api)"
    required: true
  deployment_name:
    description: "Nome do deployment (ex: api)"
    required: true
  grafana_tag:
    description: "Tag do Grafana"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cp helm-values/${{ inputs.chart_type }}/values.yaml values.yaml
        sed -i "s/<DEPLOYMENT-NAME>/${{ inputs.deployment_name }}/g" values.yaml
        sed -i "s/<GRAFANA-TAG>/${{ inputs.grafana_tag }}/g" values.yaml
        sed -i "s/<NOME-REPOSITORIO>/${{ github.event.repository.name }}/g" values.yaml
        mkdir -p .github/helm/${{ inputs.deployment_name }}
        mv values.yaml .github/helm/${{ inputs.deployment_name }}/values.yaml
      shell: bash
    
    - run: |
        RABBITMQ_BASE64=$(echo -n "${{ secrets.BROKER_AMQP }}" | base64 -w0)
        echo "${{ vars._PROPERTIES }}" >> values.properties
        echo "build.istio.egress.databases.default.port=${{ vars.DB_PORT }}" >> values.properties
        echo "build.istio.egress.databases.default.host=${{ vars.DB_HOST }}" >> values.properties
        echo "build.secrets.rabbitmq_auth_host=$RABBITMQ_BASE64" >> values.properties
      shell: bash

      