name: 'Check Variables'
description: 'Check required variables'
inputs:
  variables:
    description: 'Required variables'
    required: true

runs:
  using: composite
  steps:
  - name: Check required variables
    shell: bash
    run: |
      variables=${{ inputs.variables }}
      variables_array=$(echo "\"$variables\"" | jq -c 'split(",")')     
      for item in "${variables_array[@]}"; do
        echo "Variable: [$item]"
        if [ -z $item ]; then
            echo "❌ Input is missing!"
            exit 1
          fi
      done
