name: 'Check Variables'
description: 'Check required variables'
inputs:
  variables:
    description: 'Required variables'
    required: true

runs:
  using: composite
  steps:
  - name: Check required variables
    shell: bash
    run: |
      variables=${{ inputs.variables }}
      IFS=',' read -ra key_values <<< "$variables"
      for item in "${key_values[@]}"; do
        key="${item%%:*}"
        value="${item#*:}"

        if [ -z $value ]; then
            echo "❌" $key "is missing!"
            exit 1
          fi
      done
