name: 'Check Variables'
description: 'Check required variables'
inputs:
  variables:
    description: 'Required variables'
    required: true

runs:
  using: composite
  steps:
  - name: Check required variables
    shell: bash
    run: |
      variables=${{ inputs.variables }}
      echo 'teste' $variables
      IFS=',' read -ra key_values <<< "$variables"
      echo 'key_values' $key_values
      for item in "${key_values[@]}"; do
        echo "Key value: [$item]"

        key="${item%%:*}"
        value="${item#*:}"

        echo 'key' $key
        echo 'value' $value

        if [ -z $value ]; then
            echo "❌" $key "is missing!"
            exit 1
          fi
      done
