name: 'Create Namespace And Service Account'
description: 'creating k8s resources'
inputs:
  role_arn:
    description: 'Aws role arn'
    required: true
  namespace:
    description: 'Application name'
    required: true
  service_account_name:
    description: 'Service Account name'
    required: true
  cluster_name:
    description: 'Cluster Name'
    required: true
runs:
  using: composite
  steps:
  - name: check-values
    shell: bash
    run: |
      echo "AccountNumber: ${{ env.AWS_ACCOUNT_NUMBER }}"
      echo "Region: ${{ env.AWS_REGION }}"
      echo "Role: ${{ env.AWS_ROLE_NAME }}"
      echo "Cluster: ${{ inputs.cluster_name }}"

  - name: configure
    uses: orbitspot/actions/.github/actions/kubernetes-auth@master
    with:
        cluster_name: ${{ inputs.cluster_name }}

  - name: create-namespace
    shell: bash
    run: |
        if ! kubectl get ns ${{ inputs.namespace }} &>/dev/null; then
            kubectl create ns ${{ inputs.namespace }}
        else
            echo "Namespace ${{ inputs.namespace }} already exists."
        fi
  - name: create service account yaml
    shell: bash
    run: |
      cat <<EOT > service-account.yaml
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: ${{ inputs.role_arn }}
        name: ${{ inputs.service_account_name }}
        namespace: ${{ inputs.namespace }}
      EOT

  - name: apply service account
    shell: bash
    run: |
      kubectl apply -f service-account.yaml
