name: 'Create Namespace And Service Account'
description: 'creating k8s resources'
inputs:
  role_arn:
    description: 'Aws role arn'
    required: true
  namespace:
    description: 'Application name'
    required: true
  service_account_name:
    description: 'Service Account name'
    required: true

  aws_account_number:
    description: 'Account Number'
    required: true
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
  aws_region:
    description: 'Aws region'
    required: true
  cluster_name:
    description: 'Cluster Name'
    required: true
runs:
  using: composite
  steps:

  - name: check-values
    shell: bash
    run: |
      echo "AccountNumber: ${{ inputs.aws_account_number }}"
      echo "Region: ${{ inputs.aws_region }}"
      echo "Role: ${{ inputs.aws_role_name }}"
      echo "Cluster: ${{ inputs.cluster_name }}"

  - name: configure
    uses: orbitspot/actions/.github/actions/kubernetes-auth@v18.6
    with:
        aws_account_number: ${{ inputs.aws_account_number }}
        aws_role_name: ${{ inputs.aws_role_name }}
        aws_region: ${{ inputs.aws_region }}
        cluster_name: ${{ inputs.cluster_name }}

  - name: create-namespace
    shell: bash
    run: |
        if ! kubectl get ns ${{ inputs.namespace }} &>/dev/null; then
            kubectl create ns ${{ inputs.namespace }}
        else
            echo "Namespace ${{ inputs.namespace }} already exists."
        fi
  - name: create service account yaml
    shell: bash
    run: |
      cat <<EOT > service-account.yaml
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: ${{ inputs.role_arn }}
        name: ${{ inputs.service_account_name }}
        namespace: ${{ inputs.namespace }}
      EOT

  - name: apply service account
    shell: bash
    run: |
      kubectl apply -f service-account.yaml
