name: 'Create Namespace And Service Account'
description: 'creating k8s resources'
inputs:
  namespace:
    description: 'Application name'
    required: true
  service_account_name:
    description: 'Service Account name'
    required: true
  module:
    description: 'Module name'
    required: true
    type: string
runs:
  using: composite
  steps:
  - name: check-values
    shell: bash
    run: |
      echo "AccountNumber: ${{ env.AWS_ACCOUNT_NUMBER }}"
      echo "Region: ${{ env.CLUSTER_REGION }}"
      echo "Role: ${{ env.AWS_ROLE_NAME }}"
      echo "Cluster: ${{ env.CLUSTER_NAME }}"

  - name: configure
    uses: orbitspot/actions/.github/actions/kubernetes-auth@v21

  - name: create-namespace
    shell: bash
    run: |
        if ! kubectl get ns ${{ inputs.namespace }} &>/dev/null; then
            kubectl create ns ${{ inputs.namespace }}
        else
            echo "Namespace ${{ inputs.namespace }} already exists."
        fi
  
  - name: label namespace
    shell: bash
    run: |
      kubectl label namespace ${{ inputs.namespace }} modulo=${{ inputs.module }} --overwrite

  - name: create service account yaml
    shell: bash
    run: |
      cat <<EOT > service-account.yaml
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/${{ github.event.repository.name }}-${{ env.ENV }}
        name: ${{ inputs.service_account_name }}
        namespace: ${{ inputs.namespace }}
      EOT

  - name: apply service account
    shell: bash
    run: |
      kubectl apply -f service-account.yaml
