name: 'Helm deploy'
description: 'Deploy Helm'
inputs:
  namespace:
    description: 'Helm namespace'
    required: true
  release:
    description: 'Release'
    required: true
  chart_name:
    description: 'Chart Name'
    required: true
  chart_version:
    description: 'Chart Version'
    required: true
  sets:
    description: 'Set values'
    required: true
  helm_values:
    description: 'Helm Values'
    required: true
runs:
  using: composite
  steps:
    - name: configure
      uses: orbitspot/actions/.github/actions/kubernetes-auth@v20.6.2

    - name: Download Building files
      uses: actions/download-artifact@v4
      with:
          name: ${{ inputs.helm_values }}

    - name: Check Files
      shell: bash
      run: |
        ls -ltra

    - name: CheckValues
      shell: bash
      run: |
        cat values.yaml

    - name: Helm Install
      shell: bash
      run: |
        helm upgrade ${{ inputs.release}}  \
        --install \
        --create-namespace \
        --namespace ${{ inputs.namespace}} ${{ inputs.chart_name }} \
        --version ${{ inputs.chart_version }} \
        --set region=${{ env.CLUSTER_REGION }} \
        -f values.yaml \
        ${{ inputs.sets }}