name: 'Create Registry Docker Repository'
description: 'Create Registry Docker Repository'
inputs:
  repository:
    description: 'Aws role to be created'
    required: true
runs:
  using: composite
  steps:

  - name: Create ECR
    if: steps.check-role.outputs.repository_exists == 'false'
    shell: bash
    run: |
      aws iam create-role --role-name "${{ inputs.role }}" --assume-role-policy-document '{
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::${{ inputs.aws_account_number }}:oidc-provider/${{ inputs.cluster_oidc_issuer_url_without_https }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "${{ inputs.cluster_oidc_issuer_url_without_https }}:sub": "system:serviceaccount:${{ inputs.namespace }}:${{ inputs.service_account_name }}"
              }
            }
          }
        ]
      }'

