name: 'Parameter Store'
description: 'Parameter store'
inputs:
  environment_json:
    description: 'environment values'
    required: true
  file_name:
    description: 'file name'
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Generate JSON and set output
      shell: python
      run: |
          import json

          variables = ${{ inputs.environment_json }}
          print(variables)
          not_container_variables = ['CLUSTER_REGION', 'ENV', 'CLUSTER_NAME', 'ACCESS_KEY_CODE_ARTIFACT', 'GIT_TOKEN', 'PARAMETERS_ENCRYPT_HASH', 'SECRET_ACCESS_KEY_CODE_ARTIFACT', 
                                    'API_GATEWAY', 'AWS_ACCOUNT_NUMBER', 'AWS_ROLE_NAME', 'ISTIO_HOST', 'TERRAFORM_BUCKET', '_PROPERTIES', '_POLICY_JSON']
          result_json = {}
          for key in variables:
            value = variables[key].replace("$", "$$") # no terraform $$ é o escapamento para o $ 
            if len(value) > 0 and key not in not_container_variables: # nao adiciona variaveis sem valor
              result_json.update({key: value}) 

          with open(f"${{ inputs.file_name }}.json", "w") as outfile:
            json.dump(result_json, outfile)

    - name: Upload encrypted artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.file_name }}
        path: ${{ inputs.file_name }}.json
        retention-days: 1
