name: 'Parameter Store'
description: 'Parameter store'
inputs:
  keys:
    description: 'Environment Keys'
    required: true
  environment_json:
    description: 'environment values'
    required: true
  file_name:
    description: 'file name'
    required: true
  encrypt:
    description: 'file name'
    required: false
runs:
  using: composite
  steps:
  - name: Generate JSON and set output
    shell: bash
    run: |
        # Remove os colchetes da string
        keys=${{ inputs.keys }}
        keys=$(echo $keys | sed 's/^\[\|]$//g')

        # JSON contendo todas as variáveis de vars
        vars_json='${{ inputs.environment_json }}'

        # Inicializa o JSON
        result_json="{"

        # Converte a string em um array
        IFS=',' read -r -a array <<< "$keys"

        # Itera sobre os elementos do array
        for index in "${!array[@]}"; do
            key=$(echo "${array[$index]}" | tr -d '"') # Remove aspas
            value=$(echo "$vars_json" | jq -r ".\"$key\" // empty") # Obtém o valor da chave

            # Só adiciona se o valor não estiver vazio
            if [ -n "$value" ]; then
                # Adiciona ao JSON
                result_json="$result_json\"$key\":\"$value\","
            fi
        done

        # Remove a última vírgula e fecha o JSON
        result_json=$(echo "$result_json" | sed 's/,$//')
        result_json="$result_json}"
      
        # Debug para verificar o JSON gerado
        echo "Generated JSON: $result_json"
      
        # Define o output do step
        echo "$result_json" >> ${{ inputs.file_name }}.json


#  - name: Encrypt the file
#    shell: bash
#    run: |
#      openssl enc -aes-256-cbc -salt -in ${{ inputs.file_name }}.json -out ${{ inputs.file_name }}.json.enc -k ${{ inputs.encrypt }}

  - name: Upload encrypted artifact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.file_name }}
      path: ${{ inputs.file_name }}.json
      retention-days: 1