name: 'Terraform Parameter Store'
description: 'Terraform Parameter store'
inputs:
  terraform_bucket_name:
    description: 'Bucket'
    required: true
    default: 'terraform-orbit'
  modulo:
    description: 'Module'
    required: true
  repository:
    description: 'Repository'
    required: true
  tag:
    description: 'tag'
    required: true
  global:
    description: 'global'
    required: true

runs:
  using: composite
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/${{ env.AWS_ROLE_NAME }}
      role-session-name: ${{ env.AWS_ROLE_NAME }}
      aws-region: ${{ env.CLUSTER_REGION }}

  - name: Checkout code
    uses: actions/checkout@v4
    with:
        repository: 'orbitspot/actions'
        path: orbitspot-actions
        ref: '${{ inputs.tag }}'

  - name: Download Artifact Variables
    uses: actions/download-artifact@v4
    with:
        name: variables
        path: orbitspot-actions/terraform/parameter-store

  - name: Download Artifact
    uses: actions/download-artifact@v4
    with:
        name: secrets
        path: orbitspot-actions/terraform/parameter-store
  
  - name: Install Terraform
    shell: bash
    run: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
      terraform --version

  - name: Verify Terraform Installation
    shell: bash
    run: terraform --version

  - name: Terraform Init
    shell: bash
    run: |
      ls
      cd orbitspot-actions/terraform/parameter-store && ls
      terraform init -backend-config=bucket=${{ env.TERRAFORM_BUCKET }} -backend-config=key=parameter-store/${{ github.event.repository.name }}/${{ github.ref_name }}.tfstate -backend-config=region=us-east-1 -no-color
      
  - name: Terraform Plan
    shell: bash
    env:
      TF_VAR_region: ${{ env.CLUSTER_REGION }}
      TF_VAR_modulo: ${{ inputs.modulo }}
      TF_VAR_repository: ${{ inputs.repository }}
      TF_VAR_global: ${{ inputs.global }}
    run: |
      cd orbitspot-actions/terraform/parameter-store
      terraform plan -no-color

  - name: Terraform Apply
    shell: bash
    env:
      TF_VAR_region: ${{ env.CLUSTER_REGION }}
      TF_VAR_modulo: ${{ inputs.modulo }}
      TF_VAR_repository: ${{ inputs.repository }}
      TF_VAR_global: ${{ inputs.global }}
    run: |
      cd orbitspot-actions/terraform/parameter-store
      terraform apply -auto-approve -no-color

