name: 'Helm Upgrade'
description: 'helm upgrade or install'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
  aws_region: 
    description: 'Aws region'
    required: true
  cluster_name:
    description: 'Eks Cluster'
    required: true
  s3_chart_location:
    description: 'S3 template location'
    required: false
    default: 's3://devops.orbitspot.com/charts/'

runs:
  using: composite
  steps:

  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}


  - name: Install kubectl
    shell: bash
    run: |
      curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.7/2021-07-05/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/

  - name: Install aws-iam-authenticator
    shell: bash
    run: |
      curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.7/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      chmod +x ./aws-iam-authenticator
      sudo mv ./aws-iam-authenticator /usr/local/bin/

  - name: Set up Helm
    uses: azure/setup-helm@v4

  - name: Cache Helm plugins
    id: cache-helm-plugins
    uses: actions/cache@v4
    with:
      path: ~/.local/share/helm/plugins/
      key: ${{ runner.os }}-helm-plugins-${{ hashFiles('role.json') }}
      restore-keys: |
        ${{ runner.os }}-helm-plugins-

  - name: Install Plugins
    shell: bash
    run: |
      helm plugin install https://github.com/aslafy-z/helm-git.git
      helm plugin install https://github.com/hypnoglow/helm-s3.git


  - name: Add Helm repository
    shell: bash
    run: helm repo add orbitspot ${{ inputs.s3_chart_location }}
