module: <GRAFANA-TAG>

nodeSelector:
    nodegroup-type: ${.<NOME-REPOSITORIO>.landingpage.node_selector}

ingress:
  annotations:
    order: 1
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landingpage
                port:
                  number: 80
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landingpage
                port:
                  number: 80

csiSecrets:
  enabled: true
  serviceAccountName: "application-permission"

service:
  type: NodePort

containers:
  - name: frontend
    ports:
      - targetPort: 3000
        port: 80
        protocol: TCP
    resources:
      requests:
        cpu: ${.<NOME-REPOSITORIO>.landingpage.resources.requests.cpu}
        memory: ${.<NOME-REPOSITORIO>.landingpage.resources.requests.memory}
      limits:
        cpu: ${.<NOME-REPOSITORIO>.landingpage.resources.limits.cpu}
        memory: ${.<NOME-REPOSITORIO>.landingpage.resources.limits.memory}