module: <GRAFANA-TAG>

nodeSelector:
    nodegroup-type: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.node_selector}

jobTemplate:
    activeDeadlineSeconds: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.keda.activeDeadlineSeconds}
    backoffLimit: 3

csiSecrets:
    enabled: true
    serviceAccountName: "application-permission"

service:
    type: ClusterIP

containers:
    - name: cronjob-<REPOSITORY-NAME>
      resources:
        requests:
            cpu: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.requests.cpu}
            memory: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.requests.memory}
        limits:
            cpu: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.limits.cpu}
            memory: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.limits.memory}