ingress:
  version: 2
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: ${.<REPOSITORY-NAME>.build.acm_arn}
    alb.ingress.kubernetes.io/group.name: ${.<REPOSITORY-NAME>.build.environment}-ingress
    alb.ingress.kubernetes.io/load-balancer-name: ${.<REPOSITORY-NAME>.build.environment}-applications
  rules:
    - http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 80
            path: /
            pathType: Prefix