module: <GRAFANA-TAG>

nodeSelector:
  nodegroup-type: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.node_selector}

csiSecrets:
  enabled: true
  serviceAccountName: "application-permission"

containers:
  - name: scaledjob
    resources:
      requests:
        cpu: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.requests.cpu}
        memory: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.requests.memory}
      limits:
        cpu: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.limits.cpu}
        memory: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.resources.limits.memory}


keda:
  secrets:
    name: scaledjob-<DEPLOYMENT-NAME>

  authentication:
    name: scaledjob-<DEPLOYMENT-NAME>
    spec:
      secretTargetRef:
        - key: rabbitmq_http_host
          name: scaledjob-<DEPLOYMENT-NAME>
          parameter: host

  pollingInterval: 30
  maxReplicaCount: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.keda.maxReplicaCount}
  failedJobsHistoryLimit: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.keda.failedJobsHistoryLimit}
  successfulJobsHistoryLimit: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.keda.successfulJobsHistoryLimit}
  activeDeadlineSeconds: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.keda.activeDeadlineSeconds}
  scalingStrategy:
    strategy: eager
  triggers:
    - type: rabbitmq
      authenticationRef:
        name: scaledjob-<DEPLOYMENT-NAME>
      metadata:
        protocol: amqp
        queueName: ${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.queue_name}
        mode: QueueLength
        value: "${.<REPOSITORY-NAME>.<DEPLOYMENT-NAME>.queue_min_messages}"

service:
  type: ClusterIP