name: 'Npm Ci'
description: 'npm install and building'
inputs:
  node_version:
    description: 'Node Version'
    required: true
  install:
    description: 'Npm install'
    default: false
  customized_dockerfile:
    description: "Not empty if using the repo's Dockerfile for build"
    default: ''

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    name: Checkout
    with:
        ref: ${{ inputs.git_ref }}
        fetch-depth: 0

  - name: Set up Node.js
    uses: actions/setup-node@v4
    if: inputs.node_version != ''
    with:
        node-version: ${{ inputs.node_version }}

  - name: Npm Install
    shell: bash
    if: inputs.install
    run: |
        npm install --loglevel verbose

  - name: Npm Ci
    shell: bash
    run: |
        npm ci
        npm run build
        npm prune --production

  - name: Zip Docker Content
    shell: bash
    run: |
        mkdir -p building
        mkdir -p deps
        mv dist building/dist
        mv package.json building/package.json
        mv .github/scripts building/scripts
        mv node_modules deps/node_modules

  - name: Copy Dockerfile
    if: ${{ inputs.customized_dockerfile != '' }}
    shell: bash
    run: |
        mv ${{ inputs.customized_dockerfile }} building/docker

  - uses: vimtor/action-zip@v1.2
    with:
      files: deps
      dest: building/node_modules.zip

  - name: Upload Artifacts
    uses: actions/upload-artifact@v4
    with:
        name: building
        path: building
        retention-days: 1