name: 'Setup'
description: 'Basic config for pipeline run'
inputs:
  setup:
    description: 'api/landingpage/scaledjob/migration/etc'
    required: true
  repo_vars: # action não tem acesso às vars
    description: 'repository variables'
    required: true
  devops_config: # action não tem acesso às vars
    description: 'devops config'
    required: true
outputs:
  CLUSTER_REGION:
    description: 'cluster region'
    value: ${{ steps.set-output.outputs.CLUSTER_REGION }}
  CLUSTER_NAME:
    description: 'cluster region'
    value: ${{ steps.set-output.outputs.CLUSTER_NAME }}
  ACM_ARN:
    description: 'cluster region'
    value: ${{ steps.set-output.outputs.ACM_ARN }}
  ENV:
    description: 'cluster region'
    value: ${{ steps.set-output.outputs.ENV }}
  AWS_ACCOUNT_NUMBER:
    description: 'AWS Account Number based on branch'
    value: ${{ steps.get-aws-account.outputs.account-number }}
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Checkout script repository
      uses: actions/checkout@v4
      with:
        repository: 'orbitspot/actions'
        path: orbitspot-actions
        ref: 'v21'
    
    - name: Check required variables
      shell: bash
      env:
        variables_json: ${{ inputs.repo_vars }}
        setup: '${{ inputs.setup }}'
      run: |
        python orbitspot-actions/.github/scripts/check-required-variables.py

    - name: Fetch devops variables
      id: set-output
      uses: orbitspot/actions/.github/actions/fetch-devops-variables@v21
      with:
        devops_config: '${{ inputs.devops_config }}'
        branch: '${{ github.ref_name }}'

    - name: Get AWS Account Number
      id: get-aws-account
      uses: orbitspot/actions/.github/actions/get-aws-account-number@v21
      with:
        aws_account_number_json: ${{ fromJson(inputs.repo_vars)._AWS_ACCOUNT_NUMBER }}
