name: 'Code Artifact'
description: 'code artifact login'
inputs:
  co_login_file_name:
    description: 'co login file name'
    required: false
    default: 'co_login_commands.txt'

runs:
  using: composite
  steps:
  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/${{ env.AWS_ROLE_NAME }}
      role-session-name: ${{ env.AWS_ROLE_NAME }}
      aws-region: ${{ env.AWS_REGION }}

  - name: Verify AWS Identity
    shell: bash
    run: aws sts get-caller-identity

  - name: Log in to CodeArtifact
    shell: bash
    if: inputs.co_login_file_name != ''
    run: aws codeartifact login --tool npm --repository packages --domain seidor --namespace @seidor --dry-run > ${{ inputs.co_login_file_name }}

  - name: Log in to CodeArtifact without file
    shell: bash
    if: inputs.co_login_file_name == ''
    run: aws codeartifact login --tool npm --repository packages --domain seidor --namespace @seidor --dry-run

