name: Push node

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      grafana_tag: # vai desaparecer
        required: true
        type: string
      version:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: ''
      package_manager:
        description: 'Package manager to use (npm or yarn)'
        required: false
        type: string
        default: 'npm'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env: # global env
  AWS_ROLE_NAME: ${{ vars.AWS_ROLE_NAME }}
  AWS_REGION: ${{ vars._AWS_REGION }}

jobs:
  setup-config:
    name: Set Up Config
    runs-on: ['${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    environment: ${{ github.ref_name }}
    outputs:
      PROPERTIES: '${{ steps.properties.outputs.properties }}'
      CLUSTER_REGION: '${{ steps.set-output.outputs.CLUSTER_REGION }}'
      CLUSTER_NAME: '${{ steps.set-output.outputs.CLUSTER_NAME }}'
      ACM_ARN: '${{ steps.set-output.outputs.ACM_ARN }}'
      ENV: '${{ steps.set-output.outputs.ENV }}'
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      scaledjob-matrix: ${{ steps.set-matrix.outputs.scaledjob_matrix }}
    steps:
      - name: Set up
        id: set-output
        uses:  orbitspot/actions/.github/actions/setup-config@v20.6.0
        with:
          setup: 'api'
          repo_vars: '${{ toJson(vars) }}'
          devops_config: '${{ vars._DEVOPS_CONFIG }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - id: set-matrix
        shell: bash
        run: |
          set -e
          PROJECT_ROOT=$(git rev-parse --show-toplevel)
          SCRIPT_DIR="$PROJECT_ROOT/.github/scripts"
          scripts=($(find "$SCRIPT_DIR" -maxdepth 1 -type f -name "*.sh" -exec basename {} .sh \;))
          matrix=$(printf '%s\n' "${scripts[@]}" | jq -R . | jq -cs 'map(select(contains("cronjob") | not))')
          scaledjob_matrix=$(echo "$matrix" | jq -c '[.[] | select(. != "api")]')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "scaledjob_matrix=$scaledjob_matrix" >> $GITHUB_OUTPUT

      - name: Echo variables
        id: properties
        run: |
            united="${{ vars._PROPERTIES_API }}
            ${{ vars._PROPERTIES_SCALEDJOB }}"

            echo "===== MERGED ====="
            echo "$united"
            {
              echo "properties<<EOF"
              echo "$united"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"

  building:
    name: Building
    runs-on: [ '${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    needs: [setup-config]
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
    steps:
      - name: Building
        uses: orbitspot/actions/.github/actions/package-manager-install@v20.6.0
        with:
          node_version: '${{ inputs.version }}'
          customized_dockerfile: '${{ inputs.dockerfile_path  }}'

  generate-docker:
    name: Docker Build
    runs-on: [ '${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    environment: ${{ github.ref_name }}
    needs: [setup-config, building]
    strategy:
      matrix:
        artifacts: ${{ fromJson(needs.setup-config.outputs.matrix) }}
    permissions:
      id-token: write
      contents: read
    env:
      CLUSTER_REGION: '${{ needs.setup-config.outputs.CLUSTER_REGION }}'
      AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
    steps:
      - name: Authenticate
        uses: orbitspot/actions/.github/actions/generate-docker@v20.6.0
        with:
          deployment_name: ${{ matrix.artifacts }}
          dockerfile_path: ${{ inputs.dockerfile_path }}
          version: ${{ inputs.version }}
          build_args: '--build-arg sha=${{ github.sha }} --build-arg RUNNER=${{ matrix.artifacts }}'
          before_building: |
            cat base_script.sh scripts/${{ matrix.artifacts }}.sh > ${{ matrix.artifacts }}.sh
            cat ${{ matrix.artifacts }}.sh

  create-service-account-role: #virar action
    name: Creating Aws Resources
    runs-on: [ '${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    environment: ${{ github.ref_name }}
    needs: [setup-config, generate-docker]
    permissions:
      id-token: write
      contents: read
    env:
      CLUSTER_REGION: '${{ needs.setup-config.outputs.CLUSTER_REGION }}'
      CLUSTER_NAME: '${{ needs.setup-config.outputs.CLUSTER_NAME }}'
      ENV: '${{ needs.setup-config.outputs.ENV }}'
      AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
    steps:
      - name: create-role
        uses: orbitspot/actions/.github/actions/create-role-service-account@v20.6.0
        with:
          role: '${{ github.event.repository.name }}-${{ env.ENV }}'
          namespace: ${{ github.event.repository.name }}
          service_account_name: 'application-permission'
          policy: ${{ vars._POLICY_JSON }}

      - name: create-namespace
        uses: orbitspot/actions/.github/actions/create-namespace-and-service-account@v20.6.0
        with:
          namespace: ${{ github.event.repository.name }}
          service_account_name: 'application-permission'

  prepare-helm-replacements:
    name: Building Helm Values
    runs-on: [ '${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    environment: ${{ github.ref_name }}
    needs: [setup-config, generate-docker]
    strategy:
      matrix:
        artifacts: ${{ fromJson(needs.setup-config.outputs.matrix) }}
    permissions:
      id-token: write
      contents: read
    env:
      ACM_ARN: '${{ needs.setup-config.outputs.ACM_ARN }}'
      ENV: '${{ needs.setup-config.outputs.ENV }}'
      PROPERTIES: '${{ needs.setup-config.outputs.PROPERTIES }}'
    steps:
      - name: Preparar values.yaml
        id: prepare_helm
        uses: orbitspot/actions/.github/actions/prepare-helm-chart-values@v20.6.0
        with:
          deployment_name: ${{ matrix.artifacts }}
          grafana_tag: ${{ inputs.grafana_tag }}
        env:
          MODULE: ${{ inputs.module }}
          BROKER_AMQP: ${{ secrets.BROKER_AMQP }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_HOST: ${{ vars.DB_HOST }}
          OLD_INGRESS_HOST: ${{ vars.OLD_INGRESS_HOST }}
          VARS: ${{ toJson(vars) }}
          SECRETS: ${{ toJson(secrets) }}

  helm-cd-api:
    name: K8s Deploy api
    runs-on: [ '${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    environment: ${{ github.ref_name }}
    needs: [setup-config, prepare-helm-replacements]
    permissions:
      id-token: write
      contents: read
    env:
      CLUSTER_REGION: '${{ needs.setup-config.outputs.CLUSTER_REGION }}'
      CLUSTER_NAME: '${{ needs.setup-config.outputs.CLUSTER_NAME }}'
      ENV: '${{ needs.setup-config.outputs.ENV }}'
      AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
    steps:
      - name: helm-apply (sem ingress antigo)
        if: ${{ vars.OLD_INGRESS_HOST == '' }}
        uses: orbitspot/actions/.github/actions/helm-deploy@v20.6.0
        with:
          namespace: ${{ github.event.repository.name }}
          helm_values: helm-values-api
          release: api
          chart_name: orbitspot/orbitspot-microservices
          chart_version: 3.0.2
          sets: |
            --set environment=${{ env.ENV }} \
            --set region=${{ env.CLUSTER_REGION }} \
            --set 'containers[0].repository.image=${{ vars.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.CLUSTER_REGION }}.amazonaws.com/api-${{ github.event.repository.name }}' \
            --set 'containers[0].repository.tag=${{ github.sha }}'

      - name: helm-apply (com OLD_INGRESS_HOST)
        if: ${{ vars.OLD_INGRESS_HOST != '' }}
        uses: orbitspot/actions/.github/actions/helm-deploy@v20.6.0
        with:
          namespace: ${{ github.event.repository.name }}
          helm_values: helm-values-api
          release: api
          chart_name: orbitspot/orbitspot-microservices
          chart_version: 3.0.2
          sets: |
            --set environment=${{ env.ENV }} \
            --set region=${{ env.CLUSTER_REGION }} \
            --set 'containers[0].repository.image=${{ vars.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ env.CLUSTER_REGION }}.amazonaws.com/api-${{ github.event.repository.name }}' \
            --set 'containers[0].repository.tag=${{ github.sha }}' \
            --set ingress.rules[0].host=${{ vars.OLD_INGRESS_HOST }}

  helm-cd-scaledjob:
    name: K8s Deploy ${{ matrix.artifacts }}
    if: ${{ needs.setup-config.outputs.scaledjob-matrix != '[]' }}
    runs-on: [ '${{ github.ref_name }}', '${{ inputs.module }}', linux, self-hosted, x64]
    environment: ${{ github.ref_name }}
    needs: [setup-config, prepare-helm-replacements]
    strategy:
      matrix:
        artifacts: ${{fromJson(needs.setup-config.outputs.scaledjob-matrix) }}
    permissions:
      id-token: write
      contents: read
    env:
      CLUSTER_REGION: '${{ needs.setup-config.outputs.CLUSTER_REGION }}'
      CLUSTER_NAME: '${{ needs.setup-config.outputs.CLUSTER_NAME }}'
      ENV: '${{ needs.setup-config.outputs.ENV }}'
      AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
    steps:
      - name: helm-apply
        uses: orbitspot/actions/.github/actions/helm-deploy@v20.6.0
        with:
          namespace: ${{ github.event.repository.name }}
          helm_values: helm-values-${{ matrix.artifacts }}
          release: ${{ matrix.artifacts }}
          chart_name: orbitspot/orbitspot-job
          chart_version: 0.1.5
          sets: |
            --set environment=${{env.ENV}} \
            --set region=${{ env.CLUSTER_REGION }} \
            --set 'containers[0].repository.image=${{ vars.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{env.CLUSTER_REGION}}.amazonaws.com/${{ matrix.artifacts }}-${{ github.event.repository.name }}' \
            --set 'keda.secrets.data.rabbitmq_http_host=${{ secrets.BROKER_AMQP_SCALEDJOB_BASE64 }}' \
            --set 'containers[0].repository.tag=${{ github.sha }}' \
            --set 'containers[0].environments.SERVICE_TYPE=${{ matrix.artifacts }}'
      
      - name: Clean up machine
        shell: bash
        run: |
          rm -rf /opt/actions-runner/_work/${{ github.repository }}/*
          df -h