name: Protection

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: "Nome do Repositório que será protegido"
        required: true
        type: string

      branch_name:
        description: "Nome da branch que será utilizada na proteção"
        required: true
        default: master
        type: choice
        options:
          - master
          - develop
          - homolog


# concurrency:
#   group: '${{ github.workflow }}'
#   cancel-in-progress: true

jobs:
  terraform-init:
    name: init
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Set OAuth Token
        run: |
          git config --global url."https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_NUMBER }}:role/${{ vars.AWS_ROLE_NAME }}"
          role-session-name: "${{ vars.AWS_ROLE_NAME }}"
          aws-region: "us-east-1"
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            repository: orbitspot/infra-github-protections
            path: infra-github-protections # nome na pasta de destino dentro do runner
            ref: "master"
      
      - name: Checking folder
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          cd infra-github-protections && ls
    
      - name: Terraform Init
        shell: bash
        env:
          TF_VAR_repository_name: "${{ github.event.inputs.branch_name }}"
          TF_VAR_branch_pattern: "${{ github.event.inputs.repository_name }}"
          TF_VAR_token: "${{ secrets.GIT_TOKEN }}"

        run: |
          cd infra-github-protections/terraform/
          terraform init -backend-config=bucket=terraform-orbit -backend-config=key=branch-protections/${{  github.event.inputs.repository_name }}/${{ github.event.inputs.branch_name }}.tfstate -backend-config=region=us-east-1 -no-color
    
      - name: Terraform Plan
        shell: bash
        run: |
          cd infra-github-protections/terraform/
          terraform plan -no-color
    
      - name: Terraform Apply
        shell: bash
        run: |
          cd infra-github-protections/terraform/
