name: Validate Repository Workflows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Workflow version to update and test (e.g., v21.1.0)'
        required: true
        type: string

jobs:
  update-and-trigger:
    runs-on: ubuntu-latest
    environment: main
    strategy:
      matrix:
        repository:
          - infra-api-example
          - infra-api-scaledjob-example
          - infra-scaledjob-example
          - infra-api-migration-example
          - infra-frontend-example
          - infra-landingpage-example
          - infra-cronjob-example

    steps:
      - name: Update reusable workflow version in all branches
        run: |
          repo="${{ matrix.repository }}"
          version="${{ github.event.inputs.version }}"
          branches=("develop" "homolog" "master")

          echo "Processing repository $repo ..."

          for branch in "${branches[@]}"; do
            echo "Cloning $repo on branch $branch..."
            git clone --depth 1 --branch "$branch" "https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/orbitspot/$repo.git" || {
              echo "Branch $branch not found in $repo, skipping..."
              continue
            }
            cd "$repo"

            file=".github/workflows/push.yaml"
            if [[ -f "$file" ]]; then
              echo "Updating reusable workflow version to @$version in $file"

              sed -i "s|\(orbitspot/actions/.github/workflows/.*\.yaml\)@\([^'\"]*\)|\1@$version|g" "$file"

              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"

              if git diff --quiet "$file"; then
                echo "No changes detected in $file for branch $branch."
              else
                git add "$file"
                git commit -m "chore: update workflow version to @$version"
                git push origin "$branch"
                echo "Changes committed and pushed to branch $branch."
              fi
            else
              echo "File $file not found in repository $repo"
            fi

            cd ..
            rm -rf "$repo"
          done

      - name: Trigger workflow in all branches
        run: |
          repo="${{ matrix.repository }}"
          branches=("develop" "homolog" "master")

          for branch in "${branches[@]}"; do
            echo "Triggering workflow in $repo on branch $branch..."
            response=$(curl -s -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/orbitspot/$repo/actions/workflows/push.yaml/dispatches \
              -d "{\"ref\":\"$branch\"}")

            echo "Workflow triggered in repository $repo on branch $branch"
            echo "API Response:"
            echo "$response"
          done

      - name: Clean up machine
        shell: bash
        run: |
          rm -rf /opt/actions-runner/_work/${{ github.repository }}/*
          df -h
