name: Validar Workflows dos Repositórios

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Workflow version to update and test (ex: v20.0)'
        required: true
        type: string

jobs:
  disparar-e-validar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repositorio:
          - infra-api-example
          - infra-api-consumer-example
          - infra-scaledjob-example
          - infra-api-migration-example
          - infra-frontend-example
          - infra-landingpage-example

    steps:
      - name: Update version workflow reusable
        run: |
          repo="${{ matrix.repositorio }}"
          version="${{ github.event.inputs.version }}"

          echo "Cloning repository $repo..."
          git clone --depth 1 "https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/orbitspot/$repo.git"
          cd "$repo"

          file=".github/workflows/push.yaml"
          if [[ -f "$file" ]]; then
            echo "Updating reusable workflow version to @$version"

            # Replace any value (or empty) after @ in uses: orbitspot/actions/.github/workflows/*.yaml@XYZ
            sed -i "s|\(orbitspot/actions/.github/workflows/.*\.yaml\)@\([^'\"]*\)|\1@$version|g" "$file"

            # Set commit author
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # Check if there were changes before committing
            if git diff --quiet "$file"; then
              echo "No changes detected in $file. No commit needed."
            else
              git add "$file"
              git commit -m "chore: update workflow version to @$version"
              git push origin develop
              echo "Commit and push completed successfully."
            fi
          else
            echo "File $file not found in repository $repo"
          fi

      - name: Disparar workflow no repositório ${{ matrix.repositorio }}
        run: |
          repo="${{ matrix.repositorio }}"
          branch="develop"  
          response=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/orbitspot/$repo/actions/workflows/push.yaml/dispatches \
            -d "{\"ref\":\"$branch\"}")

          echo "✅ Workflow disparado no repositório $repo"
          echo "🧾 Resposta da API:"
          echo "$response"
